<?xml version="1.0"?>
<package format="3">
  <name>kfs_detection_nav</name>
  <version>0.0.0</version>
  <description>Detection + TF + Nav2 interface for KFS task</description>

  <maintainer email="1363920065@qq.com">Your Name</maintainer>

  <license>Apache-2.0</license>

  <!-- ROS2 build tools -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <!-- Core dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>builtin_interfaces</depend>

  <!-- For future YOLO message types add here -->
  <depend>sensor_msgs</depend>
  <depend>yolov8_ros2_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

</package>
