include_quiz_state: false
start_state: 1

quiz_result_topic: /mission/quiz_type
quiz_result_type: std_msgs/msg/Int32
quiz_wait_timeout_s: 10.0

ui_points:
  file: ui_points_fast_mode.yaml

label_hotspots:
  file: label_hotspots.yaml

base_scenario_file: tmp/base_scenario.yaml

plan_ready_topic: /mission/plan_ready
plan_ready_type: std_msgs/msg/Bool

planner_variant: front_back
max_waypoint: 4

ranking:
  prefer_direct_path_weight: 10.0
  cross_path_penalty: 5.0
  path_change_penalty: 1.0
