mission_quintuple_loader:
  ros__parameters:
    plan_ready_topic: /mission/plan_ready
    bt_config_ready_topic: /mission/bt_config_ready
    # true=等待 plan_ready_topic 触发才转换
    # 全自动任务 start_mission_full.sh 会覆盖为 /mission/quiz_plan_ready
    wait_for_trigger: true
    quintuple_yaml: /home/dog12/SCURC_Nav_Sim/src/legged_mission_planner_f_r/tmp/mission_quintuple.yaml
    bt_xml_output: /home/dog12/SCURC_Nav_Sim/src/robot_functionality/legged_mission_bt/behavior_trees/mission_hardcoded.xml
    waypoints_yaml_output: ""
    path_count: 6
    wp_count: 4
    arm_timeout: 30.0
    nav_frame_id: map
    send_p0_wp0: false              # true=保留 nav_p0_wp0, false=过滤掉
