<?xml version="1.0"?>
<package format="3">
  <name>height_control_plugins</name>
  <version>0.0.1</version>
  <description>Height control behavior tree action plugins for Nav2</description>

  <maintainer email="1363920065@qq.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>nav2_behavior_tree</depend>
  <depend>behaviortree_cpp_v3</depend>

  <export>
    <!--关键行：没有它，AMENT_PREFIX_PATH 永远不生效 -->
    <build_type>ament_cmake</build_type>

    <!-- Nav2 BT plugin description -->
    <nav2_behavior_tree
      plugin="${prefix}/share/height_control_plugins/height_control_plugins.xml" />
  </export>
</package>
