from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import yaml

from .package_paths import resolve_config_path

FIELD_IMAGE = '场地俯视图.png'
NORMALIZATION_IMAGE_PIXELS = 'image_pixels'
LABEL_HOTSPOTS_FILE = 'label_hotspots.yaml'


@dataclass(frozen=True)
class NormRect:
    norm_x0: float
    norm_y0: float
    norm_x1: float
    norm_y1: float

    @classmethod
    def from_drag(cls, x0: float, y0: float, x1: float, y1: float) -> 'NormRect':
        return cls(
            norm_x0=min(x0, x1),
            norm_y0=min(y0, y1),
            norm_x1=max(x0, x1),
            norm_y1=max(y0, y1),
        )

    @property
    def center(self) -> tuple[float, float]:
        return (self.norm_x0 + self.norm_x1) / 2.0, (self.norm_y0 + self.norm_y1) / 2.0

    def contains(self, norm_x: float, norm_y: float) -> bool:
        return (
            self.norm_x0 <= norm_x <= self.norm_x1
            and self.norm_y0 <= norm_y <= self.norm_y1
        )

    def pixel_size(self, img_width: int, img_height: int) -> tuple[int, int]:
        width = max(1, int(round((self.norm_x1 - self.norm_x0) * img_width)))
        height = max(1, int(round((self.norm_y1 - self.norm_y0) * img_height)))
        return width, height

    def fit_square_sprite_size(
        self,
        img_width: int,
        img_height: int,
        *,
        min_size: int = 8,
        fill_ratio: float = 0.9,
    ) -> int:
        pixel_w, pixel_h = self.pixel_size(img_width, img_height)
        return max(min_size, int(round(min(pixel_w, pixel_h) * fill_ratio)))

    def pixel_center(self, img_width: int, img_height: int) -> tuple[int, int]:
        center_x, center_y = self.center
        return int(round(center_x * img_width)), int(round(center_y * img_height))

    def to_dict(self) -> dict:
        return {
            'norm_x0': round(self.norm_x0, 6),
            'norm_y0': round(self.norm_y0, 6),
            'norm_x1': round(self.norm_x1, 6),
            'norm_y1': round(self.norm_y1, 6),
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, float]) -> 'NormRect':
        return cls(
            norm_x0=float(data['norm_x0']),
            norm_y0=float(data['norm_y0']),
            norm_x1=float(data['norm_x1']),
            norm_y1=float(data['norm_y1']),
        )


@dataclass
class LabelHotspotConfig:
    boxes: dict[int, NormRect]
    zones: dict[int, NormRect]

    def box_centers(self) -> dict[int, tuple[float, float]]:
        return {box_id: rect.center for box_id, rect in self.boxes.items()}

    def zone_centers(self) -> dict[int, tuple[float, float]]:
        return {zone_id: rect.center for zone_id, rect in self.zones.items()}

    def hit_box(self, norm_x: float, norm_y: float) -> int | None:
        for box_id in sorted(self.boxes):
            if self.boxes[box_id].contains(norm_x, norm_y):
                return box_id
        return None

    def hit_zone(self, norm_x: float, norm_y: float) -> int | None:
        for zone_id in sorted(self.zones):
            if self.zones[zone_id].contains(norm_x, norm_y):
                return zone_id
        return None

    def is_complete(self) -> bool:
        return len(self.boxes) == 8 and len(self.zones) == 4

    def clone(self) -> 'LabelHotspotConfig':
        return LabelHotspotConfig(boxes=dict(self.boxes), zones=dict(self.zones))


def build_label_hotspots_yaml(config: LabelHotspotConfig) -> dict:
    from .ui_assets import field_image_size

    return {
        'format_version': 1,
        'field_image': FIELD_IMAGE,
        'coordinate_system': 'normalized_field_image',
        'normalization': NORMALIZATION_IMAGE_PIXELS,
        'field_image_size': list(field_image_size()),
        'boxes': {box_id: rect.to_dict() for box_id, rect in sorted(config.boxes.items())},
        'zones': {zone_id: rect.to_dict() for zone_id, rect in sorted(config.zones.items())},
    }


def write_label_hotspots(config: LabelHotspotConfig, path: str | Path) -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open('w', encoding='utf-8') as f:
        f.write('# Generated by hotspot_editor_fr\n')
        yaml.safe_dump(build_label_hotspots_yaml(config), f, allow_unicode=True, sort_keys=False)
    return out


def load_label_hotspots(path: str | Path) -> LabelHotspotConfig:
    data = yaml.safe_load(Path(path).read_text(encoding='utf-8')) or {}
    boxes = {
        int(key): NormRect.from_dict(entry)
        for key, entry in (data.get('boxes') or {}).items()
    }
    zones = {
        int(key): NormRect.from_dict(entry)
        for key, entry in (data.get('zones') or {}).items()
    }
    return LabelHotspotConfig(boxes=boxes, zones=zones)


def load_default_label_hotspots() -> LabelHotspotConfig | None:
    path = resolve_config_path(LABEL_HOTSPOTS_FILE)
    if not path.exists():
        return None
    return load_label_hotspots(path)
