from __future__ import annotations

from pathlib import Path
from typing import Mapping, Sequence

import yaml

from .motion_planner import derive_motion_planner, is_bt_export_step
from .path_planner import SWITCH_MODE
from .state_definitions import MissionState, MissionStep
from .waypoint_config import WaypointConfig
from .waypoint_yaml_exporter import FORMAT_VERSION, PLANNER_VARIANT


def target_id_for_step(step: MissionStep) -> int:
    if step.state == MissionState.PICK and step.target_box is not None:
        return int(step.target_box)
    if step.state == MissionState.PLACE and step.target_zone is not None:
        return int(step.target_zone)
    return -1


def build_quintuple_plan(
    sequence: Sequence[MissionStep],
    *,
    waypoint_config: WaypointConfig | None = None,
) -> dict:
    del waypoint_config  # motion_planner is derived from step state/path
    quintuple_sequence: list[dict] = []
    zone_visit_count: dict[int, int] = {}
    for step in sequence:
        if not is_bt_export_step(int(step.state)):
            continue

        tid = target_id_for_step(step)

        # 归还区第二次放置时，target_id = 实际编号 + 4
        if step.state == MissionState.PLACE and step.target_zone is not None:
            zone = int(step.target_zone)
            count = zone_visit_count.get(zone, 0)
            if count >= 1:
                tid = zone + 4
            zone_visit_count[zone] = count + 1

        quintuple_sequence.append({
            'path': step.path,
            'wp': step.wp,
            'state': int(step.state),
            'target_id': tid,
            'motion_planner': derive_motion_planner(step.path, step.wp, int(step.state)),
        })
    return {
        'format_version': FORMAT_VERSION,
        'planner_variant': PLANNER_VARIANT,
        'switch_mode': SWITCH_MODE,
        'sequence': quintuple_sequence,
    }


def write_quintuple_yaml(plan: Mapping, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        f.write('# Generated by legged_mission_planner_f_r\n')
        yaml.safe_dump(dict(plan), f, allow_unicode=True, sort_keys=False)
    return path


def export_quintuple(
    sequence: Sequence[MissionStep],
    output_path: str | Path,
    *,
    waypoint_config: WaypointConfig | None = None,
) -> dict:
    plan = build_quintuple_plan(sequence, waypoint_config=waypoint_config)
    write_quintuple_yaml(plan, output_path)
    return plan
