from __future__ import annotations

from pathlib import Path
from typing import Mapping, Sequence

import yaml

from .state_definitions import MissionState, MissionStep
from .waypoint_config import WaypointConfig
from .waypoint_yaml_exporter import FORMAT_VERSION, PLANNER_VARIANT


def target_id_for_step(step: MissionStep) -> int:
    if step.state == MissionState.PICK and step.target_box is not None:
        return int(step.target_box)
    if step.state == MissionState.PLACE and step.target_zone is not None:
        return int(step.target_zone)
    return -1


def build_quintuple_plan(
    sequence: Sequence[MissionStep],
    switch_mode: str,
    *,
    waypoint_config: WaypointConfig | None = None,
) -> dict:
    quintuple_sequence: list[dict] = []
    for step in sequence:
        limit_yaw = False
        if waypoint_config is not None:
            meta = waypoint_config.get_meta(step.path, step.wp)
            if meta is not None:
                limit_yaw = meta.limit_yaw
        quintuple_sequence.append({
            'path': step.path,
            'wp': step.wp,
            'state': int(step.state),
            'target_id': target_id_for_step(step),
            'limit_yaw': limit_yaw,
        })
    return {
        'format_version': FORMAT_VERSION,
        'planner_variant': PLANNER_VARIANT,
        'switch_mode': switch_mode,
        'sequence': quintuple_sequence,
    }


def write_quintuple_yaml(plan: Mapping, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        f.write('# Generated by legged_mission_planner_f_r\n')
        yaml.safe_dump(dict(plan), f, allow_unicode=True, sort_keys=False)
    return path


def export_quintuple(
    sequence: Sequence[MissionStep],
    switch_mode: str,
    output_path: str | Path,
    *,
    waypoint_config: WaypointConfig | None = None,
) -> dict:
    plan = build_quintuple_plan(sequence, switch_mode, waypoint_config=waypoint_config)
    write_quintuple_yaml(plan, output_path)
    return plan
