from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence

import yaml

from .motion_planner import derive_motion_planner
from .ui_assets import (
    FIELD_IMAGE,
    NORMALIZATION_IMAGE_PIXELS,
    correct_legacy_norm_y,
    field_image_size,
    needs_legacy_norm_y_correction,
)

FORMAT_VERSION = 1
PLANNER_VARIANT = 'front_back'
COORDINATE_SYSTEM = 'normalized_field_image'


@dataclass(frozen=True)
class WaypointUI:
    path_id: int
    wp_index: int
    norm_x: float
    norm_y: float
    state: int = 0           # 0=QUIZ, 1=TRANSIT, 2=PICK, 3=PLACE
    target_id: int = -1      # PICK: box 0-7, PLACE: zone 0-3, 其他: -1
    motion_planner: int = 0  # 0=corridor, 1=forward, 2=backward

    @property
    def waypoint_id(self) -> str:
        return f'{self.path_id}-{self.wp_index}'


def waypoint_id(path_id: int, wp_index: int) -> str:
    return f'{path_id}-{wp_index}'


def _motion_planner_from_entry(
    path_id: int,
    wp_index: int,
    state: int,
    entry: dict,
) -> int:
    if 'motion_planner' in entry:
        return int(entry['motion_planner'])
    if 'limit_yaw' in entry:
        return derive_motion_planner(path_id, wp_index, state)
    return derive_motion_planner(path_id, wp_index, state)


def build_ui_points_yaml(paths: Mapping[int, Sequence[WaypointUI]]) -> dict:
    sorted_paths = sorted(paths.items(), key=lambda item: item[0])
    paths_out: dict[int, list[dict]] = {}
    for path_id, waypoints in sorted_paths:
        if not waypoints:
            continue
        paths_out[path_id] = [
            {
                'id': wp.waypoint_id,
                'norm_x': round(wp.norm_x, 6),
                'norm_y': round(wp.norm_y, 6),
                'state': wp.state,
                'target_id': wp.target_id,
                'motion_planner': wp.motion_planner,
            }
            for wp in sorted(waypoints, key=lambda w: w.wp_index)
        ]
    return {
        'format_version': FORMAT_VERSION,
        'planner_variant': PLANNER_VARIANT,
        'field_image': FIELD_IMAGE,
        'coordinate_system': COORDINATE_SYSTEM,
        'normalization': NORMALIZATION_IMAGE_PIXELS,
        'field_image_size': list(field_image_size()),
        'paths': paths_out,
    }


def build_mission_plan_hardcoded_yaml(paths: Mapping[int, Sequence[WaypointUI]]) -> dict:
    sequence: list[dict] = []
    for path_id in sorted(paths.keys()):
        for wp in sorted(paths[path_id], key=lambda w: w.wp_index):
            sequence.append({
                'path': wp.path_id,
                'wp': wp.wp_index,
                'state': wp.state,
                'target_id': wp.target_id,
                'motion_planner': wp.motion_planner,
            })

    nav: dict[str, dict] = {}
    for path_id in sorted(paths.keys()):
        for wp in sorted(paths[path_id], key=lambda w: w.wp_index):
            nav[wp.waypoint_id] = {
                'frame_id': 'map',
                'x': None,
                'y': None,
                'yaw': None,
            }

    return {
        'format_version': FORMAT_VERSION,
        'planner_variant': PLANNER_VARIANT,
        'sequence': sequence,
        'nav': nav,
    }


def collect_waypoint_ids(paths: Mapping[int, Sequence[WaypointUI]]) -> list[str]:
    ids: list[str] = []
    for path_id in sorted(paths.keys()):
        for wp in sorted(paths[path_id], key=lambda w: w.wp_index):
            ids.append(wp.waypoint_id)
    return ids


def write_yaml(data: dict, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        f.write('# Generated by waypoint_editor_fr\n')
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False)
    return path


def export_waypoint_yamls(
    paths: Mapping[int, Sequence[WaypointUI]],
    ui_points_out: str | Path,
    mission_plan_out: str | Path,
) -> tuple[Path, Path]:
    ui_path = write_yaml(build_ui_points_yaml(paths), ui_points_out)
    bt_path = write_yaml(build_mission_plan_hardcoded_yaml(paths), mission_plan_out)
    return ui_path, bt_path


def load_ui_points(path: str | Path) -> dict[int, list[WaypointUI]]:
    data = yaml.safe_load(Path(path).read_text(encoding='utf-8')) or {}
    apply_legacy_y = needs_legacy_norm_y_correction(data)
    raw_paths = data.get('paths', {})
    result: dict[int, list[WaypointUI]] = {}
    for path_key, entries in raw_paths.items():
        path_id = int(path_key)
        waypoints: list[WaypointUI] = []
        for entry in entries or []:
            wp_id = str(entry['id'])
            _, wp_str = wp_id.split('-', 1)
            wp_index = int(wp_str)
            state = int(entry.get('state', 0))
            norm_x = float(entry['norm_x'])
            norm_y = float(entry['norm_y'])
            if apply_legacy_y:
                norm_y = correct_legacy_norm_y(norm_y)
            waypoints.append(
                WaypointUI(
                    path_id=path_id,
                    wp_index=wp_index,
                    norm_x=norm_x,
                    norm_y=norm_y,
                    state=state,
                    target_id=int(entry.get('target_id', -1)),
                    motion_planner=_motion_planner_from_entry(path_id, wp_index, state, entry),
                )
            )
        result[path_id] = sorted(waypoints, key=lambda w: w.wp_index)
    return result
